//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryBama
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUYER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUYER()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
        }
    
        public string username { get; set; }
        public string phone { get; set; }
        public int address { get; set; }
        public string default_payment { get; set; }
        public int default_store_id { get; set; }
    
        public virtual ADDRESS ADDRESS1 { get; set; }
        public virtual GROCERYSTORE GROCERYSTORE { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
    }
}
