//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryBama
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERED_BY
    {
        public int order_id { get; set; }
        public string deliverer_username { get; set; }
        public string is_delivered { get; set; }
        public string delivery_time { get; set; }
        public string delivery_date { get; set; }
    
        public virtual ORDERR ORDERR { get; set; }
        public virtual USER USER { get; set; }
    }
}
