//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryBama
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GroceryBamaEntities1 : DbContext
    {
        public GroceryBamaEntities1()
            : base("name=GroceryBamaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDRESS> ADDRESSes { get; set; }
        public virtual DbSet<BUYER> BUYERs { get; set; }
        public virtual DbSet<GROCERYSTORE> GROCERYSTOREs { get; set; }
        public virtual DbSet<ITEM> ITEMs { get; set; }
        public virtual DbSet<ORDERR> ORDERRs { get; set; }
        public virtual DbSet<SYSTEMINFORMATION> SYSTEMINFORMATIONs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<DELIVERED_BY> DELIVERED_BY { get; set; }
        public virtual DbSet<MANAGE> MANAGES { get; set; }
        public virtual DbSet<ORDERFROM> ORDERFROMs { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTs { get; set; }
        public virtual DbSet<SELECTITEM> SELECTITEMs { get; set; }
    }
}
