//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryBama
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.SELECTITEM = new HashSet<SELECTITEM>();
            this.GROCERYSTORE = new HashSet<GROCERYSTORE>();
        }
    
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string food_group { get; set; }
        public string exp_date { get; set; }
        public int quantity { get; set; }
        public double listed_price { get; set; }
        public double wholesale_price { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SELECTITEM> SELECTITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROCERYSTORE> GROCERYSTORE { get; set; }
    }
}
