//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryBama
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERR()
        {
            this.DELIVERED_BY = new HashSet<DELIVERED_BY>();
            this.SELECTITEM = new HashSet<SELECTITEM>();
            this.USER = new HashSet<USER>();
        }
    
        public int order_id { get; set; }
        public string delivery_instructions { get; set; }
        public string delivery_time { get; set; }
        public string order_placed_date { get; set; }
        public string order_placed_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERED_BY> DELIVERED_BY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SELECTITEM> SELECTITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USER { get; set; }
    }
}
